# Generated by Django 5.0.1 on 2026-02-18 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_identifier', models.CharField(blank=True, help_text='Anonymisierte Patienten-ID', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_json', models.JSONField(help_text='Alle Antworten als JSON')),
                ('ess_total', models.IntegerField(blank=True, help_text='Epworth Sleepiness Scale Gesamtscore (0-24)', null=True)),
                ('ess_band', models.CharField(blank=True, choices=[('normal', 'Normal (0-9)'), ('erhöht', 'Erhöht (10-15)'), ('ausgeprägt', 'Ausgeprägt (≥16)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.questionnairesession')),
            ],
            options={
                'verbose_name': 'Answer Set',
                'verbose_name_plural': 'Answer Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('schema_json', models.JSONField(help_text='JSON Schema mit Fragen und Struktur')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.AddField(
            model_name='questionnairesession',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='questionnaires.questionnairetemplate'),
        ),
    ]
